/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tlc200bot;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.telegram.telegrambots.ApiContextInitializer;
import org.telegram.telegrambots.meta.TelegramBotsApi;
import org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException;

public class Launcher
{
	private static final Logger _log = LoggerFactory.getLogger(Launcher.class.getName());

	public static void main(String[] args)
	{
		System.out.println("starting...");
		ServerConfig.load();
		Database.start();

		ApiContextInitializer.init();
		TelegramBotsApi botsApi;
		try
		{
			botsApi = new TelegramBotsApi(
					ServerConfig.EXTERNAL_URL,
					ServerConfig.INTERNAL_URL
			);
			botsApi.registerBot(new BotCore());
		}
		catch (TelegramApiRequestException e)
		{
			e.printStackTrace();
		}
	}
}
